# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70864d468f808569b353c5b6e7da8787083360754aaae1ec214234f00be8d021b397b01b2edc6eafc8db3a52dc11d638d6df1836249f729b7bded44f1d4e285

test:
  secret_key_base: ba4b0134b3fe7e864a74fec387f250b17935f659cf9dae89476b080892f76d19e7a39b155b504c360e01fdc381ddd0c0b0b454dab0bd0282dde8ec6244c691df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
